name: Run Colab Notebook

on:
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual
  schedule:
    - cron: '0 3 * * *'  # Menjalankan setiap hari pada pukul 9 AM (UTC)

jobs:
  run_colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install papermill

      - name: Run Notebook
        run: |
          papermill https://github.com/ErzAP-maker/erza_ap-public/.github/workflows/run-colab.yml
